backend:
  name: git-gateway
  branch: main

media_folder: "static/img" # Folder where user uploaded files should go
public_folder: "img"

# media_library:
  # name: uploadcare
  # config:
    # publicKey: a73a170cb5cdef662983
    # multiple: false
    # tabs: 'file camera url facebook gdrive'
    # effects: 'crop,rotate,enhance,grayscale'
    # imageShrink: '2000x2000'
    # previewStep: true
    # clearable: true


collections:
  - name: 'info'
    label: 'Informatie'
    folder: 'content/page'
    delete: false
    create: true
    path: '{{title}}'
    fields:
      - { label: 'Titel', name: 'title', widget: 'string' }
      - { label: 'Omschrijving', name: 'description', widget: 'string' }
      - { label: 'Publicatie datum', name: 'date', widget: 'datetime' }
      - { label: 'Laatst aangepast', name 'lastmod', widget: 'datetime' }
      - { label: 'Inhoud', name: 'body', widget: 'markdown' }
      - name: 'menu'
        widget: 'object'
        fields:
          - name: 'main'
            widget: 'object'
            fields:
              - { label: 'Waar in het menu', name: 'weight', widget: 'number', default: -90, value_type: 'int', min: -100, max: 100, step: 10 }
              - { label: 'Icoon (Font Awesome)', name: 'pre', widget: 'string', default: 'user' }
  - name: 'blog'
    label: 'Blog'
    folder: 'content/post'
    create: true
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
    fields:
        - { label: 'Status', name: 'status', widget: 'select', options: ['Published', 'Featured', 'Draft'], default: 'Published' }
        - { label: 'Verborgen', name: 'hidden', widget: 'boolean', required: false }
        - { label: 'Titel', name: 'title', widget: 'string' }
        - { label: 'Omschrijving', name: 'description', widget: 'string' }
        - { label: 'Publicatie datum', name: 'date', widget: 'datetime' }
        - { label: 'Laatst aangepast', name 'lastmod', widget: 'datetime' }
        - { label: 'Auteur', name: 'author', widget: 'string' }
        - { label: 'Tags', name: 'tags', widget: 'list' }
        - label: 'Categoriën'
          name: 'categories'
          widget: 'list'
          required: false
          fields:
            - label: 'Category'
              name: 'category'
              widget: 'relation'
              collection: 'postCategories'
              searchFields: ['title']
              valueField: 'title'
        - { label: 'Image'  , name: 'image', widget: image, required: false }
        - { label: 'Inhoud', name: 'body', widget: 'markdown' }
        - label: 'Opties'
          name: 'options'
          widget: 'object'
          fields:
        - { label: 'Commentaar', name: 'comments', widget: 'boolean', default: true, required: false }